pbutils: fix compilation error in macro expansion
Fix:
 "encoding-target.c: In function 'get_locale': encoding-target.c:421: error:
 used struct type value where scalar is required"

Rename a local variable from 'loc' to 'locale' since GST_LOG declares
a variable called loc internally.